version: $(APPVEYOR_REPO_TAG_NAME).{build}
image: Visual Studio 2022
configuration: Release
platform:
- Win32
shallow_clone: true

before_build:
- cmd: >-
    build\beforebuild.bat

build:
  project: bld-vs2015\EngineToolset_vs2015.sln
  verbosity: minimal

after_build:
- cmd: >-
    build\afterbuild.bat

artifacts:
- path: .\dist\xray_re-tools_$(appveyor_repo_tag_name)_$(cor_plat).7z
  name: release

deploy:
- provider: GitHub
  auth_token:
    secure: YPR+FMFdOEmn4M5OwUPWZ/QZkR9ppZ5Ka/1I1ImpcJyGDjBaDUn0h2ZuBFAKP0Dr
  artifact: release
  on:
    appveyor_repo_tag: true
