OBJ_DIR := _obj
ROOT_DIR := ../..
SRC_DIR := ..

TARGET := aiwrapper
SOURCES := \
	$(SRC_DIR)/aiwrapper.cxx \
	$(SRC_DIR)/syncer.cxx \
	$(SRC_DIR)/syncer_game_spawn.cxx \
	$(SRC_DIR)/syncer_level_game.cxx \
	$(SRC_DIR)/syncer_level_gct.cxx \
	$(SRC_DIR)/syncer_level_spawn.cxx

include $(ROOT_DIR)/bld-mingw/engine.mk
