"%ProgramFiles%\WinRAR\winrar.exe" a ms3dsdk184.zip ./ms3dsdk.txt
"%ProgramFiles%\WinRAR\winrar.exe" a ms3dsdk184.zip ./zipsdk.bat
"%ProgramFiles%\WinRAR\winrar.exe" a ms3dsdk184.zip ./ms3dsdk/msASCIIExporter/ 
"%ProgramFiles%\WinRAR\winrar.exe" a ms3dsdk184.zip ./ms3dsdk/msASCIIImporter/
"%ProgramFiles%\WinRAR\winrar.exe" a ms3dsdk184.zip ./ms3dsdk/msRawImporter/
"%ProgramFiles%\WinRAR\winrar.exe" a ms3dsdk184.zip ./ms3dsdk/msRawExporter/
"%ProgramFiles%\WinRAR\winrar.exe" a ms3dsdk184.zip ./ms3dsdk/msTextImporter/
"%ProgramFiles%\WinRAR\winrar.exe" a ms3dsdk184.zip ./ms3dsdk/msTextExporter/
"%ProgramFiles%\WinRAR\winrar.exe" a ms3dsdk184.zip ./ms3dsdk/specs/
"%ProgramFiles%\WinRAR\winrar.exe" a ms3dsdk184.zip ./msLib/msLib.h
"%ProgramFiles%\WinRAR\winrar.exe" a ms3dsdk184.zip ./msLib/msPlugin.h
"%ProgramFiles%\WinRAR\winrar.exe" a ms3dsdk184.zip ./msLib/lib/msModelLib.lib
